trigger:
  batch: true
  branches:
    include:
    - "*"
  paths:
    exclude:
    - README.md

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: "Github - Azure Pipelines"
      name: CultClassik/azdo-private-tf-templates
      ref: refs/heads/main

variables:
# - name: tflint_version
#   value: 0.34.1
- name: tf_cli_version
  value: 1.1.6

stages:
- template: stages-terraform-infra.yml@templates
  parameters:
    stages:
      - stage:
        workspace: terraform-github-mgmt
        azdo_approval_environment: production
