name: Terraform Configuration Run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  terraform:
    uses: Diehlabs/.github/workflows/terraform-local.yml@v0.0.3
