name: Ansible CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  terraform:
    uses: Diehlabs/shared-workflows/.github/workflows/terraform-local.yml@v0.1.0
    with:
      tf_version: '1.2.9'
      tfe_token: ${{ secrets.TF_API_TOKEN }}